# Generated by Django 3.1.2 on 2021-02-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20201106_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_assignment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
