# Generated by Django 3.1.2 on 2021-02-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210215_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
